# Generated by Django 4.1.3 on 2022-11-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=14)),
                ('fono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=20)),
                ('ex_liceo', models.CharField(max_length=12)),
                ('carrera', models.CharField(max_length=15)),
            ],
        ),
    ]
