# Generated by Django 4.1.3 on 2022-12-06 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('fono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('ex_liceo', models.CharField(max_length=20)),
                ('carrera', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'alumno',
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('fono', models.CharField(max_length=15)),
                ('nivelAcademico', models.CharField(max_length=50)),
                ('anos_exp', models.IntegerField()),
                ('especialidad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docente',
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_seccion', models.CharField(max_length=8)),
                ('alumnos_asignados', models.ManyToManyField(to='evaApp.alumno')),
                ('docente_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaApp.docente')),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
                'db_table': 'seccion',
                'ordering': ['cod_seccion'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sala', models.CharField(choices=[('Ñ401', 'Ñ401'), ('Ñ402', 'Ñ402'), ('Ñ403', 'Ñ403'), ('Ñ404', 'Ñ404'), ('Ñ405', 'Ñ405'), ('Ñeica', 'Ñeica')], max_length=5)),
                ('cod_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaApp.seccion')),
                ('docente_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaApp.docente')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'sala',
                'ordering': ['cod_sala'],
            },
        ),
        migrations.CreateModel(
            name='DirectorC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=20)),
                ('seccion_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaApp.seccion')),
            ],
            options={
                'verbose_name': 'Director de Carrera',
                'verbose_name_plural': 'Directores de carrera',
                'db_table': 'director_carrera',
                'ordering': ['apellido'],
            },
        ),
    ]
