# Generated by Django 4.1.3 on 2022-12-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='docente_cargo',
        ),
        migrations.RemoveField(
            model_name='directorc',
            name='seccion_cargo',
        ),
        migrations.AddField(
            model_name='directorc',
            name='seccion_cargo',
            field=models.ManyToManyField(to='evaApp.seccion'),
        ),
    ]
